language: python
python:
  - "2.7"
  - "3.3"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: cd testing && python runtests.py
services:
  - postgresql
after_success: coveralls
