language:
  python

python:
  - "2.7"
  - "3.3"

env:
  - DJANGO=1.7

install:
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet
  - pip install coveralls --quiet

script:
  - cd testing && python runtests.py
  - coverage run --source=filtered_contenttypes python runtests.py

services:
  - postgresql

after_success:
  coveralls
