language:
  python

python:
  - 2.7
  - 3.5

env:
  - DJANGO=1.7
  - DJANGO=1.8

install:
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet
  - pip install coveralls --quiet

script:
  - cd testing && python runtests.py
  - coverage run --source=filtered_contenttypes runtests.py

services:
  - postgresql

after_success:
  coveralls

matrix:
  exclude:
    - python: 3.5
      	env: DJANGO=1.7
