language:
  python

python:
  - "2.7"
  - "3.3"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - cd testing && python runtests.py
  - coverage run --source=filtered_contenttypes python runtests.py

services:
  - postgresql

after_success:
  coveralls
